name: Poros Priject CI

on:
  push:
    branches:
      - "master"

jobs:
  build_android_and_glue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v2

      - name: Create local.properties with SDK path
        working-directory: ./xposed_loader
        run: |
           echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties    

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        working-directory: ./xposed_loader
        run: ./gradlew assembleDebug


      - name: Install CMake
        if: ${{ env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Setup Android NDK R25
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false

      - name: build ndk project
        working-directory: ./core
        run: ./build.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: copy and compress binary and dex files
        run: ./copy_files.sh

      - name: Upload script files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: poros_shell_cmd.tar.gz
          asset_name: poros_shell_cmd.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload build products to artifacts
        uses: actions/upload-artifact@v4
        with:
          path: output/
          name: build_assets
          retention-days: 1
          if-no-files-found: error
